chat message
Waite-Development/Chat-App pull request #10
Opened 2023-10-09 22:29 UTC by d-waite

2023-10-09 22:29 UTC, d-waite commented
Current dependencies on/for this PR:
* main
  * **PR #9** <a href="https://app.graphite.dev/github/pr/Waite-Development/Chat-App/9" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #10** <a href="https://app.graphite.dev/github/pr/Waite-Development/Chat-App/10" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Waite-Development/Chat-App/10?utm_source=stack-comment).

2023-10-10 00:49 UTC, twaite commented on apps/client/.turbo/turbo-dev.log
> -
hmm, this file should be ignored,  I thought I added it to the gitignore, but maybe you used this before syncing with my code?

2023-10-10 00:54 UTC, twaite requested changes
Just need to remove the turbo file, the other changes look fine

2023-10-11 18:36 UTC, twaite approved these changes

2023-10-12 01:16 UTC, d-waite commented
### Merge activity

* **Oct 11, 9:16 PM**: @d-waite started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Waite-Development/Chat-App/10).

2023-10-12 01:17 UTC, merged